name: psancistest01
favicon: null
layout_spectrum: 0.52476
typography_spectrum: 0.26224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b5c4cb'
    - '#fc0d1b'
    - '#121212'
    - '#4c4794'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
