name: psancistest01
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#aaa2a0'
    - '#837c72'
    - '#443f39'
    - '#190000'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
