name: psancistest01
favicon: null
layout_spectrum: 0.23291503079235554
typography_spectrum: 0.936710593290627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b5c4cb'
    - '#fc0d1b'
    - '#121212'
    - '#4c4794'
  brandStrength: 0.8125
  lightness: 0.29774500406347215
  saturation: 0.9334841885138303
  rhythmicContrast: 0.3821891569532454
purpose: []
